# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruction.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='instruction.proto',
  package='instruction',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11instruction.proto\x12\x0binstruction\"\x19\n\x17\x41llInstructioinsRequest\"Q\n\x18\x41llInstructioinsResponse\x12\x35\n\nthumbnails\x18\x01 \x03(\x0b\x32!.instruction.InstructionThumbnail\"v\n\x14InstructionThumbnail\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x12\n\nstep_count\x18\x05 \x01(\r\x12\x0c\n\x04size\x18\x06 \x01(\r\" \n\x12InstructionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"I\n\x13InstructionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\"\n\x06slides\x18\x02 \x03(\x0b\x32\x12.instruction.Slide\"O\n\x05Slide\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\ttransform\x18\x02 \x01(\t\x12\x12\n\nmedia_type\x18\x03 \x01(\r\x12\x11\n\tmedia_url\x18\x04 \x01(\t\"\x17\n\x05\x43hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x1a\n\x0cMediaRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x8d\x02\n\x0bInstruction\x12\x63\n\x12GetAllInstructions\x12$.instruction.AllInstructioinsRequest\x1a%.instruction.AllInstructioinsResponse\"\x00\x12U\n\x0eGetInstruction\x12\x1f.instruction.InstructionRequest\x1a .instruction.InstructionResponse\"\x00\x12\x42\n\rDownloadMedia\x12\x19.instruction.MediaRequest\x1a\x12.instruction.Chunk\"\x00\x30\x01\x62\x06proto3'
)




_ALLINSTRUCTIOINSREQUEST = _descriptor.Descriptor(
  name='AllInstructioinsRequest',
  full_name='instruction.AllInstructioinsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=59,
)


_ALLINSTRUCTIOINSRESPONSE = _descriptor.Descriptor(
  name='AllInstructioinsResponse',
  full_name='instruction.AllInstructioinsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thumbnails', full_name='instruction.AllInstructioinsResponse.thumbnails', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=142,
)


_INSTRUCTIONTHUMBNAIL = _descriptor.Descriptor(
  name='InstructionThumbnail',
  full_name='instruction.InstructionThumbnail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='instruction.InstructionThumbnail.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='instruction.InstructionThumbnail.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='instruction.InstructionThumbnail.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='instruction.InstructionThumbnail.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step_count', full_name='instruction.InstructionThumbnail.step_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='instruction.InstructionThumbnail.size', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=262,
)


_INSTRUCTIONREQUEST = _descriptor.Descriptor(
  name='InstructionRequest',
  full_name='instruction.InstructionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='instruction.InstructionRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=296,
)


_INSTRUCTIONRESPONSE = _descriptor.Descriptor(
  name='InstructionResponse',
  full_name='instruction.InstructionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='instruction.InstructionResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slides', full_name='instruction.InstructionResponse.slides', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=371,
)


_SLIDE = _descriptor.Descriptor(
  name='Slide',
  full_name='instruction.Slide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='instruction.Slide.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transform', full_name='instruction.Slide.transform', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='media_type', full_name='instruction.Slide.media_type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='media_url', full_name='instruction.Slide.media_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=452,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='instruction.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='instruction.Chunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=477,
)


_MEDIAREQUEST = _descriptor.Descriptor(
  name='MediaRequest',
  full_name='instruction.MediaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='instruction.MediaRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=505,
)

_ALLINSTRUCTIOINSRESPONSE.fields_by_name['thumbnails'].message_type = _INSTRUCTIONTHUMBNAIL
_INSTRUCTIONRESPONSE.fields_by_name['slides'].message_type = _SLIDE
DESCRIPTOR.message_types_by_name['AllInstructioinsRequest'] = _ALLINSTRUCTIOINSREQUEST
DESCRIPTOR.message_types_by_name['AllInstructioinsResponse'] = _ALLINSTRUCTIOINSRESPONSE
DESCRIPTOR.message_types_by_name['InstructionThumbnail'] = _INSTRUCTIONTHUMBNAIL
DESCRIPTOR.message_types_by_name['InstructionRequest'] = _INSTRUCTIONREQUEST
DESCRIPTOR.message_types_by_name['InstructionResponse'] = _INSTRUCTIONRESPONSE
DESCRIPTOR.message_types_by_name['Slide'] = _SLIDE
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['MediaRequest'] = _MEDIAREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AllInstructioinsRequest = _reflection.GeneratedProtocolMessageType('AllInstructioinsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLINSTRUCTIOINSREQUEST,
  '__module__' : 'instruction_pb2'
  # @@protoc_insertion_point(class_scope:instruction.AllInstructioinsRequest)
  })
_sym_db.RegisterMessage(AllInstructioinsRequest)

AllInstructioinsResponse = _reflection.GeneratedProtocolMessageType('AllInstructioinsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ALLINSTRUCTIOINSRESPONSE,
  '__module__' : 'instruction_pb2'
  # @@protoc_insertion_point(class_scope:instruction.AllInstructioinsResponse)
  })
_sym_db.RegisterMessage(AllInstructioinsResponse)

InstructionThumbnail = _reflection.GeneratedProtocolMessageType('InstructionThumbnail', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTIONTHUMBNAIL,
  '__module__' : 'instruction_pb2'
  # @@protoc_insertion_point(class_scope:instruction.InstructionThumbnail)
  })
_sym_db.RegisterMessage(InstructionThumbnail)

InstructionRequest = _reflection.GeneratedProtocolMessageType('InstructionRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTIONREQUEST,
  '__module__' : 'instruction_pb2'
  # @@protoc_insertion_point(class_scope:instruction.InstructionRequest)
  })
_sym_db.RegisterMessage(InstructionRequest)

InstructionResponse = _reflection.GeneratedProtocolMessageType('InstructionResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUCTIONRESPONSE,
  '__module__' : 'instruction_pb2'
  # @@protoc_insertion_point(class_scope:instruction.InstructionResponse)
  })
_sym_db.RegisterMessage(InstructionResponse)

Slide = _reflection.GeneratedProtocolMessageType('Slide', (_message.Message,), {
  'DESCRIPTOR' : _SLIDE,
  '__module__' : 'instruction_pb2'
  # @@protoc_insertion_point(class_scope:instruction.Slide)
  })
_sym_db.RegisterMessage(Slide)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'instruction_pb2'
  # @@protoc_insertion_point(class_scope:instruction.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

MediaRequest = _reflection.GeneratedProtocolMessageType('MediaRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEDIAREQUEST,
  '__module__' : 'instruction_pb2'
  # @@protoc_insertion_point(class_scope:instruction.MediaRequest)
  })
_sym_db.RegisterMessage(MediaRequest)



_INSTRUCTION = _descriptor.ServiceDescriptor(
  name='Instruction',
  full_name='instruction.Instruction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=508,
  serialized_end=777,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllInstructions',
    full_name='instruction.Instruction.GetAllInstructions',
    index=0,
    containing_service=None,
    input_type=_ALLINSTRUCTIOINSREQUEST,
    output_type=_ALLINSTRUCTIOINSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetInstruction',
    full_name='instruction.Instruction.GetInstruction',
    index=1,
    containing_service=None,
    input_type=_INSTRUCTIONREQUEST,
    output_type=_INSTRUCTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadMedia',
    full_name='instruction.Instruction.DownloadMedia',
    index=2,
    containing_service=None,
    input_type=_MEDIAREQUEST,
    output_type=_CHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSTRUCTION)

DESCRIPTOR.services_by_name['Instruction'] = _INSTRUCTION

# @@protoc_insertion_point(module_scope)
