# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import server_pb2 as server__pb2


class VirtualAssistantStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAllInstructions = channel.unary_unary(
        '/virtual_assistant.VirtualAssistant/GetAllInstructions',
        request_serializer=server__pb2.AllInstructioinsRequest.SerializeToString,
        response_deserializer=server__pb2.AllInstructioinsResponse.FromString,
        )
    self.GetInstruction = channel.unary_unary(
        '/virtual_assistant.VirtualAssistant/GetInstruction',
        request_serializer=server__pb2.InstructionRequest.SerializeToString,
        response_deserializer=server__pb2.InstructionResponse.FromString,
        )
    self.DownloadMedia = channel.unary_stream(
        '/virtual_assistant.VirtualAssistant/DownloadMedia',
        request_serializer=server__pb2.MediaRequest.SerializeToString,
        response_deserializer=server__pb2.Chunk.FromString,
        )
    self.LastModified = channel.unary_unary(
        '/virtual_assistant.VirtualAssistant/LastModified',
        request_serializer=server__pb2.InstructionRequest.SerializeToString,
        response_deserializer=server__pb2.Timestamp.FromString,
        )


class VirtualAssistantServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAllInstructions(self, request, context):
    """Request thumbnails to all available instructions
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInstruction(self, request, context):
    """Request instruction by id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DownloadMedia(self, request, context):
    """Request media folder in zip format
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LastModified(self, request, context):
    """Check when the object was modified last time
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VirtualAssistantServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAllInstructions': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllInstructions,
          request_deserializer=server__pb2.AllInstructioinsRequest.FromString,
          response_serializer=server__pb2.AllInstructioinsResponse.SerializeToString,
      ),
      'GetInstruction': grpc.unary_unary_rpc_method_handler(
          servicer.GetInstruction,
          request_deserializer=server__pb2.InstructionRequest.FromString,
          response_serializer=server__pb2.InstructionResponse.SerializeToString,
      ),
      'DownloadMedia': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadMedia,
          request_deserializer=server__pb2.MediaRequest.FromString,
          response_serializer=server__pb2.Chunk.SerializeToString,
      ),
      'LastModified': grpc.unary_unary_rpc_method_handler(
          servicer.LastModified,
          request_deserializer=server__pb2.InstructionRequest.FromString,
          response_serializer=server__pb2.Timestamp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'virtual_assistant.VirtualAssistant', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class WebEditorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DownloadInstruction = channel.unary_stream(
        '/virtual_assistant.WebEditor/DownloadInstruction',
        request_serializer=server__pb2.InstructionRequest.SerializeToString,
        response_deserializer=server__pb2.Chunk.FromString,
        )
    self.UploadInstructions = channel.stream_unary(
        '/virtual_assistant.WebEditor/UploadInstructions',
        request_serializer=server__pb2.Chunk.SerializeToString,
        response_deserializer=server__pb2.Status.FromString,
        )
    self.LastModified = channel.unary_unary(
        '/virtual_assistant.WebEditor/LastModified',
        request_serializer=server__pb2.InstructionRequest.SerializeToString,
        response_deserializer=server__pb2.Timestamp.FromString,
        )


class WebEditorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DownloadInstruction(self, request, context):
    """Download Instruction from server to web-editor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadInstructions(self, request_iterator, context):
    """Upload instruction(s) from web-editor to server
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LastModified(self, request, context):
    """Check when the object was modified last time
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WebEditorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DownloadInstruction': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadInstruction,
          request_deserializer=server__pb2.InstructionRequest.FromString,
          response_serializer=server__pb2.Chunk.SerializeToString,
      ),
      'UploadInstructions': grpc.stream_unary_rpc_method_handler(
          servicer.UploadInstructions,
          request_deserializer=server__pb2.Chunk.FromString,
          response_serializer=server__pb2.Status.SerializeToString,
      ),
      'LastModified': grpc.unary_unary_rpc_method_handler(
          servicer.LastModified,
          request_deserializer=server__pb2.InstructionRequest.FromString,
          response_serializer=server__pb2.Timestamp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'virtual_assistant.WebEditor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
